bakery-shop/mac/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bakery-shop/shop/urls.py
from django.urls import path
from . import views
app_name='shop'
urlpatterns = [
    

    path("", views.index, name="index"),

    path("add_cart/<int:myid>/", views.add_cart, name="add_cart"),
    path("update_cart/<int:myid>/<oper>/", views.update_cart, name="update_cart"),  

    path("search/", views.search, name="search"), 
    
   
    path("products/<int:myid>", views.productView, name="ProductView"),

    path("checkout/", views.checkout, name="Checkout"),

    path("about/", views.about, name="AboutUs"),
    path("contact/", views.contact, name="ContactUs"),

    path("<cat_name>/", views.shop, name="home"),

   
]

bakery-shop/shop/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Product(models.Model):
    product_name = models.CharField(max_length=50)
    category = models.CharField(max_length=50, default="")
    subcategory = models.CharField(max_length=50, default="")
    price = models.IntegerField(default=0)
    desc = models.CharField(max_length=300,default="nothing is to describe")
    pub_date = models.DateField()
    image = models.ImageField(upload_to='shop/images', default="")
    cart=models.BooleanField(default=False)
    qty=models.IntegerField(default=0)
    total=models.IntegerField(default=1)


    def __str__(self):
        return self.product_name

class Contact(models.Model):
    msg_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=70, default="")
    phone = models.CharField(max_length=70, default="")
    desc = models.CharField(max_length=500, default="")


    def __str__(self):
        return self.name

class Orders(models.Model):
    order_id = models.AutoField(primary_key=True)
    items_json = models.CharField(max_length=5000,default='none')
    qty=models.IntegerField(default=0)
    name = models.CharField(max_length=111)
    phone = models.CharField(max_length=70, default="")
    email = models.CharField(max_length=70, default="")
    state = models.CharField(max_length=111)
    zip_code = models.CharField(max_length=111)
    city = models.CharField(max_length=111)
    address = models.CharField(max_length=11)
    pub_date = models.DateTimeField(default=timezone.now)
    # created_at = models.DateTimeField(False, True, editable=False)

    def __str__(self):
        return self.name

bakery-shop/shop/views.py
from django.shortcuts import render,redirect
from .models import Product, Contact, Orders
from math import ceil
import json
from django.http import HttpResponse
# Create your views here.

def add_cart(request,myid):
   total=0
   pro=Product.objects.filter(id=myid)
   for q in pro:
        pro_cat=q.category
        qty=q.qty
        price=q.price
       
   qty=qty+1
   total=qty*price
   pro.update(cart=True,qty=qty,total=total)
   return redirect('shop:home',cat_name=pro_cat)


def update_cart(request,myid,oper):
    pro=Product.objects.filter(id=myid)
    for q in pro:
        pro_cat=q.category
        qty=q.qty
        total=q.total
        price=q.price

    if oper=='minus':
        qty=qty-1
        if qty==0:
            pro.update(qty=0,total=0,cart=False)
        total=qty*price
        pro.update(qty=qty,total=total)
    else:
        qty=qty+1
        total=qty*price
        pro.update(qty=qty,total=total)

    return redirect('shop:home',cat_name=pro_cat)

def index(request):
    return render(request, 'shop/home.html')

def shop(request,cat_name):
    allProds = []
    prod = Product.objects.filter(category=cat_name)
    n = len(prod)
    nSlides = n // 4 + ceil((n / 4) - (n // 4))
    allProds.append([prod, range(1, nSlides), nSlides])
    params = {'allProds':allProds}
    return render(request, 'shop/index.html', params)


def about(request):
    return render(request, 'shop/about.html')


def contact(request):
    if request.method=="POST":
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        phone = request.POST.get('phone', '')
        desc = request.POST.get('desc', '')
        contact = Contact(name=name, email=email, phone=phone, desc=desc)
        contact.save()
    return render(request, 'shop/contact.html')


def tracker(request):
   return render(request, 'shop/tracker.html')


def search(request):
    # return HttpResponse('helllo searched page is here!')
    searched=request.GET.get('q')
    products=Product.objects.filter(product_name__contains=searched)
    return render(request, 'shop/search.html',{'products':products})


def productView(request, myid):

    # Fetch the product using the id
    product = Product.objects.filter(id=myid)
    return render(request, 'shop/prodView.html', {'product':product[0]})


def checkout(request):
    qty=0
    item=''
    every=''
    data=Product.objects.filter(qty__gt=0)
    for d in data:
        qty=d.qty
        item=d.product_name
        every=every+item+'--'+str(qty)+','

    total=0
    for i in data:
        total+=i.total
    if request.method=="POST":
        items_json = request.POST.get('itemsJson', '')
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        address = request.POST.get('address1', '') + " " + request.POST.get('address2', '')
        city = request.POST.get('city', '')
        state = request.POST.get('state', '')
        zip_code = request.POST.get('zip_code', '')
        phone = request.POST.get('phone', '')
        order = Orders(items_json=every,qty=qty,name=name, email=email, address=address, city=city,
                       state=state, zip_code=zip_code, phone=phone)
        order.save()
        thank = True
        data=Product.objects.filter(qty__gt=0)
        data.update(qty=0,cart=False,total=0)
        return render(request, 'shop/checkout.html',{'thank':thank})
    return render(request, 'shop/checkout.html',{'data':data,'total':total})

bakery-shop/shop/templates/shop/about.html
{% extends 'shop/basic.html' %}
{% block title%} About Us{% endblock %}
{% block body %}
<main role="main">
  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <div class="container">
      <h1 class="display-3">Online Bakery Shop</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis perferendis minus dicta iste iure repellendus
        inventore totam. Totam a non explicabo nostrum rem nemo corrupti maiores repellendus, vel deleniti! Vitae
        blanditiis repellat sint harum.</p>
      <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more »</a></p>
    </div>
  </div>
  <div class="container">
    <!-- Example row of columns -->
    <hr>
  </div> <!-- /container -->
</main>
<footer class="text-center fixed-bottom text-white" style="background-color: #caced1;">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright:
    <a class="text-white" href="#">Backry Shop</a>
  </div>
  <!-- Copyright -->
</footer>

{% endblock %}

bakery-shop/shop/templates/shop/basic.html
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
      integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
      crossorigin="anonymous"
    />

    <title>{% block title%} {% endblock %}</title>
    <style>
      {% block css %} {% endblock %}
    </style>
  </head>
  <body>

    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/shop/">Online Bakery Shop</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/shop/"
              >Home <span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/shop/about"
              >About <span class="sr-only"></span></a
            >
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/shop/contact"
              >Contact<span class="sr-only"></span></a
            >
          </li>
        </ul>
        <form
          class="form-inline my-2 my-lg-0"
          method="get"
          action="{% url 'shop:search' %}"
        >
          <input
            class="form-control  mr-sm-2"
            type="search"
            name="q"
            placeholder="Search"
            aria-label="Search"
          />
          <button class="btn btn-sm btn-outline-success my-2 my-sm-0" type="submit">
            Search
          </button>
        </form>
        <button
          type="button"
          class="btn btn-sm btn-secondary mx-2"
          id="popcart"
          data-container="body"
          data-toggle="popover"
          data-placement="bottom"
          data-html="true"
          data-content="Vivamus
sagittis lacus vel augue laoreet rutrum faucibus."
        >
          Cart
        </button>
      </div>
    </nav>
    {% block body %} {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
      integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
      integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
      crossorigin="anonymous"
    ></script>
    {% block js %}{% endblock %}
  </body>
</html>

bakery-shop/shop/templates/shop/checkout.html
{% extends 'shop/basic.html' %}
{% block title%} Checkout{% endblock %}
{% block body %}
<br>
<div class="container">
    <div class="row">
        <div class="col-md-4 order-md-2 mb-4">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
                <div class="col my-4">
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-muted">Your cart</span>
                        <span class="badge badge-secondary badge-pill">!</span>
                    </h4>
                    {% if thank %}
                    <h1>Your order is palced successfully</h1>
                    {% else %}
                    <ul class="list-group mb-3">
                        {% if data %}
                            {% for i in data %}
                        <li class="list-group-item d-flex justify-content-between lh-condensed">
                            <div>
                                <h4 class="my-0">{{i.product_name}}</h4>
                                <small class="text-muted">Quantity: {{i.qty}}</small>
                            </div>
                            <span class="text-muted">₹{{i.price}}</span>
                        </li>
            

                            {% endfor %}
                            {% endif %}
                            <li class="list-group-item d-flex justify-content-between bg-light">
                                <div class="text-success">
                                    <h6 class="my-0">Promo code</h6>
                                    <small>EXAMPLECODE</small>
                                </div>
                                <span class="text-success">-₹5</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between">
                                <span>Total (INR)</span>
                                <strong>₹{{total}}</strong>
                            </li>
                        </ul>
                        <form class="card p-2">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Promo code">
                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-secondary">Redeem</button>
                                </div>
                            </div>
                        </form>
                   
                    {% endif %}

                </div>

        </div>
        <div class="col-md-8 order-md-1">
            <h2>Billing address</h2>
            <form method="post" action="/shop/checkout/">
                {% csrf_token %}
                <input type="hidden" name="itemsjson" id="itemsjson">
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="inputname">Name</label>
                        <input type="name" name="name" class="form-control" id="name" placeholder="Name" required>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="inputEmail4">Email</label>
                        <input type="email" class="form-control" id="email" placeholder="Email" name="email" required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputAddress">Address</label>
                    <input type="text" name="address1" class="form-control" id="address1" placeholder="1234 Main St" required>
                </div>
                <div class="form-group">
                    <label for="inputAddress2">Address line 2</label>
                    <input type="text" name="address2" class="form-control" id="address2"
                        placeholder="Apartment, studio, or floor">
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="inputCity">City</label>
                        <input type="text" class="form-control" id="city" name="city">
                    </div>
                    <div class="form-group col-md-4">
                        <label for="inputState">State</label>
                        <input type="text" class="form-control" id="state" placeholder="Enter State" name="state">
                    </div>
                    <div class="form-group col-md-2">
                        <label for="inputZip">Zip</label>
                        <input type="text" class="form-control" id="zip_code" name="zip_code">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputZip">Phone Number</label>
                    <input type="tel" class="form-control" id="phone" name="phone">
                </div>
                <hr class="mb-4">
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="same-address">
                        <label class="custom-control-label" for="same-address">Shipping address is the same as my
                            billing address</label>
                    </div>
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="save-info">
                        <label class="custom-control-label" for="save-info">Save this information for next time</label>
                    </div>
                    <hr class="mb-4">

                    <h4 class="mb-3">Payment</h4>

                    <div class="d-block my-3">
                        <div class="custom-control custom-radio">
                            <input id="credit" name="paymentMethod" type="radio" class="custom-control-input" checked
                                required>
                            <label class="custom-control-label" for="credit">Credit card</label>
                        </div>
                        <div class="custom-control custom-radio">
                            <input id="debit" name="paymentMethod" type="radio" class="custom-control-input" required>
                            <label class="custom-control-label" for="debit">Debit card</label>
                        </div>
                        <div class="custom-control custom-radio">
                            <input id="paypal" name="paymentMethod" type="radio" class="custom-control-input" required>
                            <label class="custom-control-label" for="paypal">PayPal</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="cc-name">Name on card</label>
                            <input type="text" class="form-control" id="cc-name" placeholder="" required>
                            <small class="text-muted">Full name as displayed on card</small>
                            <div class="invalid-feedback">
                                Name on card is required
                            </div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="cc-number">Credit card number</label>
                            <input type="text" class="form-control" id="cc-number" placeholder="" required>
                            <div class="invalid-feedback">
                                Credit card number is required
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3 mb-3">
                            <label for="cc-expiration">Expiration</label>
                            <input type="text" class="form-control" id="cc-expiration" placeholder="" required>
                            <div class="invalid-feedback">
                                Expiration date required
                            </div>
                        </div>
                        <div class="col-md-3 mb-3">
                            <label for="cc-cvv">CVV</label>
                            <input type="text" class="form-control" id="cc-cvv" placeholder="" required>
                            <div class="invalid-feedback">
                                Security code required
                            </div>
                        </div>
                    </div>
                    <hr class="mb-4">
                <button type="submit" class="btn btn-sm btn-primary">CheckOut</button>
            </form>
        </div>
    </div>
</div>
<br>
<br>
<hr>
<footer class="text-center fixed-bottom text-white" style="background-color: #caced1;">
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2020 Copyright:
      <a class="text-white" href="#">Backry Shop</a>
    </div>
    <!-- Copyright -->
  </footer>
{%if thank %}

{% endif %}
{% endblock %}

bakery-shop/shop/templates/shop/footer.html
<footer class="text-center fixed-bottom text-white" style="background-color: #caced1;">
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2022 Copyright:
      <a class="text-white" href="#">Backry Shop</a>
    </div>
    <!-- Copyright -->
  </footer>

bakery-shop/shop/templates/shop/index.html
{% extends 'shop/basic.html' %}
{% block css %}


body{background:#eee}.ratings i{font-size: 16px;color: red}.strike-text{color: red;text-decoration:
line-through}.product-image{width: 200px; height: 200px;}.dot{height: 7px;width: 7px;margin-left: 6px;margin-right:
6px;margin-top:
3px;background-color: blue;border-radius: 50%;display: inline-block}.spec-1{color: #938787;font-size:
15px}h5{font-weight: 400}.para{font-size: 16px}

{% endblock %}
{% block body %}
{% load static %}
<br>
<div class="container">
    <!--Slideshow starts here -->
    {% for product, range, nSlides in allProds %}
    <h5 class="my-2">A Wide Range of {{product.0.category}} -Items</h5>
    <div class="row">
        <div id="demo{{forloop.counter}}" class="col carousel slide my-1" data-ride="carousel">
            <ul class="carousel-indicators">
                <li data-target="#demo{{forloop.counter}}" data-slide-to="0" class="active"></li>
                {% for i in range %}
                <li data-target="#demo{{forloop.parentloop.counter}}" data-slide-to="{{i}}"></li>
                {% endfor %}
            </ul>
            <div class="container mt-1 mb-4">
                <div class="d-flex justify-content-center row">
                    {% for i in product %}
                    <div class="container my-2 mt-1 mb-4 col-md-10">
                        <div class="row p-2 bg-white border rounded mt-2">
                            <div class="col-md-3 mt-1"><img class="img-fluid img-responsive rounded product-image"
                                    src="/media/{{i.image}}"></div>
                            <div class="col-md-6 mt-1">
                                <h5>{{i.product_name}}</h5>
                                <div class="d-flex flex-row">
                                    <div class="ratings mr-2"><i class="fa fa-star"></i><i class="fa fa-star"></i><i
                                            class="fa fa-star"></i><i class="fa fa-star"></i></div>
                                </div>
                                <div class="mt-1 mb-1 spec-1"><span>100% Veg</span><span class="dot"></span><span>Fast
                                        Delevry</span><span class="dot"></span><span>Healthy food<br></span></div>
                                <p class="text-justify text-truncate para mb-0">{{i.desc|slice:"0:53"}}...<br><br></p>
                            </div>

                            <div class="align-items-center align-content-center col-md-3 border-left mt-1">
                                <div class="d-flex flex-row align-items-center">
                                    <h4 class="mr-1">₹{{i.price}}.99</h4><span class="strike-text">₹21.99</span>
                                </div>
                                <h6 class="text-success">Free shipping</h6>
                                {% if i.cart %}
                                <center>

                                    <a href="/shop/update_cart/{{i.id}}/minus"><button id='minus" + item + "'
                                            class='btn btn-sm btn-primary minus'>-</button> </a>
                                    <span>{{i.qty}}</span>
                                    <a href=" /shop/update_cart/{{i.id}}/plus"> <button id='plus" + item + "'
                                            class='btn btn-sm btn-primary plus'> +
                                        </button></a>

                                    {% else %}
                                    <div class="d-flex flex-column mt-4">
                                        <span id="divpr{{i.id}}" class="divpr">
                                            <a href="{% url 'shop:add_cart' i.id %}"><button id="pr{{i.id}}"
                                                    class="btn btn-sm btn-primary">Add To Cart</button></a>
                                        </span>
                                </center>
                                {% endif %}
                                <a class="d-flex flex-column mt-2" href="/shop/products/{{i.id}}"><button
                                        id="qv{{i.id}}" class="btn btn-outline-primary btn-sm mt-2">Details</button></a>
                            </div>
                        </div>

                    </div>

                </div>
                {% if forloop.counter|divisibleby:4 and forloop.counter > 0 and not forloop.last %}
            </div>
            <div class="carousel-item">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endfor %}
</div>
<br>
<br>
<hr>
<footer class="text-center fixed-bottom text-white" style="background-color: #caced1;">
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2022 Copyright:
        <a class="text-white" href="#">Backry Shop</a>
    </div>
    <!-- Copyright -->
</footer>
{% endblock %}
{% block js %}
<script>
    $('#popcart').popover();
    popStr = "</div> <a href='/shop/checkout'><button class='btn btn-primary' id ='checkout'>Checkout</button>"
    // "</a> <button class='btn btn-primary' onclick='clearCart()' id ='clearCart'>Clear Cart</button>     "
    document.getElementById('popcart').setAttribute('data-content', popStr);

    $('#popcart').popover('show');
</script>

{% endblock %}

bakery-shop/shop/templates/shop/prodView.html
{% extends 'shop/basic.html' %}

{% block css %}


body{
    background:#eee
}

img{
    width: 300px;
    height: 300px;
}

{% endblock %}

{% block title%} {{product.product_name}} - My Awesome Cart{% endblock %}
{% block body %}

<div class="container py-3">
    <div class="title h1 text-center">Details of {{product.product_name}}</div>
    <!-- Card Start -->
    <div class="card">
        <div class="row ">

            <div style="padding: 20px; margin: 20px;" class="col-md-6 px-3">
                <div class="card-block px-6">
                    <h4 class="card-title">{{product.product_name}}</h4>
                    <h3 class="mr-1">₹{{product.price}}.99</h4>
                    <p class="card-text">
                        {{product.desc}}
                    </p>
                    <br>
                    <div class="row my-4">
                        <a href="{% url 'shop:add_cart' product.id %}"> <button class="btn btn-sm btn-outline-primary mx-3">Add To
                                Cart</button></a>
                                <a href="{% url 'shop:add_cart' product.id %}"> <button class="btn btn-sm btn-outline-primary">Buy Now</button> </a>
                    </div>
                </div>
            </div>
            <!-- Carousel start -->
            <div class="col-md-5">
                <div id="" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img style="margin: 20px;" class="d-block" src="/media/{{product.image}}" alt="">
                        </div>
                    </div>
                </div>
            </div>
            <!-- End of carousel -->
        </div>
    </div>
    <!-- End of card -->

</div>

<footer class="text-center fixed-bottom text-white" style="background-color: #caced1;">
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2020 Copyright:
      <a class="text-white" href="#">Backry Shop</a>
    </div>
    <!-- Copyright -->
  </footer>
{% endblock %}




{% block js %}
<script>
    console.log('working');
    if (localStorage.getItem('cart') == null) {
        var cart = {};
    }
    else {
        cart = JSON.parse(localStorage.getItem('cart'));
        document.getElementById('cart').innerHTML = Object.keys(cart).length;
    }
    $('.cart').click(function () {
        console.log('clicked');
        var idstr = this.id.toString();
        console.log(idstr);
        if (cart[idstr] != undefined) {
            cart[idstr] = cart[idstr] + 1;
        }
        else {
            cart[idstr] = 1;
        }
        console.log(cart);
        localStorage.setItem('cart', JSON.stringify(cart));
        document.getElementById('cart').innerHTML = Object.keys(cart).length;
    });
    $('#popcart').popover();
    document.getElementById("popcart").setAttribute('data-content', '<h5>Cart for your items in my shopping cart</h5>');
</script>
{% endblock %}

bakery-shop/shop/templates/shop/search.html
{% extends 'shop/basic.html' %}

{% block title%}Product Search{% endblock %}
{% block body %}

<style>
    img {
        width: 200px;
        height: 250px;
        padding: 10px;
        margin: 10px;
    }
</style>
<br>
<div class="container">
    <div class="row">
        {% for i in products %}
        <div class="col-xs-3 col-sm-3 col-md-3">
            <div class="card align-items-center" style="width: 18rem;">
                <img src='/media/{{i.image}}' class="card-img-top " alt="...">
                <div class="card-body">
                    <h5 class="card-title" id="namepr{{i.id}}">{{i.product_name}}</h5>
                    <p id="pricepr{{i.id}}">{{i.price}}.00</p>
                    <p class="card-text">{{i.desc|slice:"0:25"}}...</p>

                    {% if i.cart %}
                    <a href="/shop/update_cart/{{i.id}}/minus"><button id='minus" + item + "'
                            class='btn btn-primary minus'>-</button> </a>
                    <span>{{i.qty}}</span>
                    <a href="/shop/update_cart/{{i.id}}/plus"> <button id='plus" + item + "'
                            class='btn btn-primary plus'> + </button></a>

                    {% else %}
                    <span id="divpr{{i.id}}" class="">
                        <a href="{% url 'shop:add_cart' i.id %}"><button id="pr{{i.id}}"
                                class="btn btn-sm btn-outline-primary cart">Add To Cart</button></a>
                    </span>
                    {% endif %}

                    <a href="/shop/products/{{i.id}}"><button id="qv{{i.id}}"
                            class="btn btn-sm btn-outline-success cart">Details</button></a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<br>
<br>
<hr>
<footer class="text-center fixed-bottom text-white" style="background-color: #caced1;">
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2020 Copyright:
      <a class="text-white" href="#">Backry Shop</a>
    </div>
    <!-- Copyright -->
  </footer>

{% endblock %}